### ISSUE TITLE
http://localhost:8090/  打开失败

### ISSUE THREAD

**Issue by shujikemobile** [xiaoze-smirk/easy-springboot#2]
问题： courseTypeList         list.typeId     list.typeName  这三个地方有编译报错，但是能运行成功，显示不出来界面，http://localhost:8090/  打开失败

提示信息：
Cannot resolve 'courseTypeList' less... (⌘F1) 
Validates unresolved references and invalid expressions

正文：

 <div>
            <span>课程类型:</span>
            <select name="courseType.typeId">
                <option>=请选择=</option>
                <option th:each="list:${courseTypeList}" th:value="${list.typeId}" th:text="${list.typeName}"></option>
            </select>
        </div>

问题： courseTypeList         list.typeId     list.typeName  这三个地方有编译报错，但是能运行成功，显示不出来界面，http://localhost:8090/  打开失败

**Comment by xiaoze-smirk** [comment]
不好意思，隔这么久了，我觉得你可能已经解决了，我配置了context-path: /ssm，所以正确的网址应该是http://localhost:8090/ssm

**Comment by shujikemobile** [comment]
还是非常感谢你的答复，谢谢！
